{% set data= load_setup_py_data() %}

package:
  name: rubintv
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - run_rubintv = lsst.ts.rubintv.run_rubintv:run_rubintv

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  run:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - boto3
    - jinja2
    - fastapi
    - starlette
    - uvicorn
    - pydantic
    - websockets
    - asgi-lifespan
    - pydantic-settings
    - nodejs
